export const FETCH_PEOPLE_LIST = 'FETCH_PEOPLE_LIST'
export const ENTER_PERSON_IN_ZONE = 'ENTER_PERSON_IN_ZONE'
export const EXIT_PERSON_IN_ZONE = 'EXIT_PERSON_IN_ZONE'
export const FETCH_ZONE_INFORMATION = 'FETCH_ZONE_INFORMATION'
